# Generated by Django 3.0.8 on 2020-07-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('usermail', models.CharField(max_length=200)),
                ('userpassword', models.CharField(max_length=100)),
                ('userdatentime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
