# Generated by Django 3.0.8 on 2020-07-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCreate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogtitle', models.CharField(max_length=30)),
                ('blogdescription', models.CharField(max_length=2000)),
                ('blogimage', models.ImageField(upload_to='Images/')),
            ],
        ),
    ]
