# Generated by Django 3.0.8 on 2020-07-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcreate',
            name='id',
        ),
        migrations.AddField(
            model_name='blogcreate',
            name='blogid',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogcreate',
            name='blogimage',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
