# Generated by Django 3.0.8 on 2020-07-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200703_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcreate',
            name='blogimage',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
