# Generated by Django 3.0.8 on 2020-07-05 15:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200705_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcreate',
            name='bloguser',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
